# Generated by Django 2.1.7 on 2019-03-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hassan',
            new_name='Crud',
        ),
    ]
